version = 0.1
[default.deploy.parameters]
stack_name = "joriapp-erp-backend"
resolve_s3 = true
s3_prefix = "joriapp-erp-backend"
region = "ap-northeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
